### ISSUE TITLE
I am new to unity so plz dont roast me

### ISSUE THREAD

**Issue by megasushi18** [roguecode/Unity-Simple-SRT#4]
I am unsure on how and where to use the call function.  Could you please clarify? Thank you

**Comment by roguecode** [comment]
Hey, checkout ExampleScene.unity which is a working example, and let me know if you still don't come right.

**Comment by megasushi18** [comment]
Is there any specific reason why the coroutine call is different than the one that was posted in the readme ?

**Comment by roguecode** [comment]
In the example it is using FindObjectOfType<SubtitleDisplayer>() which will find any GameObject in the scene with a SubtitleDisplayer component on it. Whereas in the readme it is assuming that you already have a reference to one.

**Comment by megasushi18** [comment]
Ah okay I see, do you think this can be used to show subtitles in vr as well, if so how would you implement it.

**Comment by roguecode** [comment]
I assume so, since you'd still be using the normal Unity UI stuff, but I've never done it.
