### ISSUE TITLE
I need some help 

### ISSUE THREAD

**Issue by megasushi18** [roguecode/Unity-Simple-SRT#6]
Hi, I know this is not really related to this but I need help writing an srt parser for text mesh pro as the default text does not allow me to reduce the font to a decimal size.  I was wondering if you could assist me in writing such a script.  Thank you!

**Comment by roguecode** [comment]
Checkout SubtitleDisplayer.cs. It does what you need, you'll just need to change it a bit for TextMeshPro.


From: megasushi18
Sent: Thursday, July 25, 7:52 PM
Subject: [roguecode/Unity-Simple-SRT] I need some help  (#6)
To: roguecode/Unity-Simple-SRT
Cc: Subscribed


Hi, I know this is not really related to this but I need help writing an srt parser for text mesh pro as the default text does not allow me to reduce the font to a decimal size. I was wondering if you could assist me in writing such a script. Thank you!

**Comment by megasushi18** [comment]
Ah okay, I was wondering if you could change it for me because I have zero familiarity with C#.   I tried to change the variable definitions for TextMeshPro and it said that the definitions did not exist.  I am unsure on what to do in addition to that,

**Comment by roguecode** [comment]
I haven't used TextMeshPro, but you likely don't have the right using (near the top of the file) for that namespace. 
If you're using an IDE like Visual Studio or VSCode you can click the class that is underlined red and then click the little lightbulb and click the suggestion to add the using.

**Comment by megasushi18** [comment]
GREAT! I just got it working.  I just had to import TMPro using using and also had to change the definition of the functions.  I'm so grateful that I took AP CS this year the java knowledge I had really came in handy.  Thank you for your help
